"""Tables for docs/G-C1b_addendum_welds.md from probes/gc1b_weld_bracket_eval.json, probes/gc1b_weld_bracket.json
and checks/gc1b_verdict.json (numbers only). Writes docs/G-C1b_addendum_welds_numbers.md."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
E = json.load(open(ROOT / "probes" / "gc1b_weld_bracket_eval.json"))
B = json.load(open(ROOT / "probes" / "gc1b_weld_bracket.json"))
V = json.load(open(ROOT / "checks" / "gc1b_verdict.json"))
SER = list(V["K_hifi_fine"])
out = []
w = out.append
w("<!-- generated by probes/gc1b_weld_bracket_tables.py -->\n")
w("### Welds as meshed (fine mesh; leg and reach in mm)\n")
w("| Series | throat | leg | up the flange: stamped | kept | dropped | volume: stamped | kept | dropped |")
w("|---|---|---|---|---|---|---|---|---|")
chk = json.load(open(ROOT / "probes" / "tstub_weld_check.json"))
rec = {(r["variant"], r["series"], r["mesh_level"]): r for r in B["runs"]}
for n in SER:
    s = chk[f"{n} fine"]
    k, d = rec.get(("kept", n, "fine")), rec.get(("dropped", n, "fine"))
    cells = [n, f"{s['a_w']:.0f}", f"{s['leg']:.2f}", f"{s['reach_on_flange_mm']:.2f}",
             f"{k['weld']['reach_on_flange_mm']:.2f}" if k else "n/a",
             f"{d['weld']['reach_on_flange_mm']:.2f}" if d else "n/a",
             f"{s['volume_over_exact']:.3f}",
             f"{k['weld']['volume_over_exact']:.3f}" if k else "n/a",
             f"{d['weld']['volume_over_exact']:.3f}" if d else "n/a"]
    w("| " + " | ".join(cells) + " |")
w("\n### Stiffness of the model (kN/mm)\n")
w("| Series | stamped medium | kept medium | dropped medium | stamped fine | kept fine | dropped fine | kept / stamped, fine |")
w("|---|---|---|---|---|---|---|---|")
for n in SER:
    row = [f"{V['K_hifi_medium'][n]:.2f}"]
    for v in ("kept", "dropped"):
        r = rec.get((v, n, "medium")); row.append(f"{r['K_kN_per_mm']:.2f}" if r else "n/a")
    row.append(f"{V['K_hifi_fine'][n]:.2f}")
    for v in ("kept", "dropped"):
        r = rec.get((v, n, "fine")); row.append(f"{r['K_kN_per_mm']:.2f}" if r else "n/a")
    r = rec.get(("kept", n, "fine"))
    row.append(f"{r['K_kN_per_mm'] / V['K_hifi_fine'][n]:.3f}" if r else "n/a")
    w(f"| {n} | " + " | ".join(row) + " |")
w("\n### Mesh change, fine over medium\n")
w("| Series | stamped | kept | dropped |")
w("|---|---|---|---|")
for n in SER:
    row = [f"{100 * V['mesh_change_fine_vs_medium_hifi'][n]:+.1f}%"]
    for v in ("kept", "dropped"):
        m = E.get(f"{v} mesh_change_fine_vs_medium")
        row.append(f"{100 * m[n]:+.1f}%" if m else "n/a")
    w(f"| {n} | " + " | ".join(row) + " |")
w("\n### G-C1b's criteria applied to each variant\n")
w("| Run | geometric mean R | inside [0.80, 1.25] (17 needed) | outside | C2 | would-be verdict |")
w("|---|---|---|---|---|---|")
st = V["primary"]
w(f"| stamped, fine (the verdict) | {st['gm_R']:.3f} | {st['n_inside']} | {', '.join(st['outside'])} | {st['C2']} | {st['verdict']} |")
for key in ("kept fine", "dropped fine", "kept medium", "dropped medium"):
    if key in E:
        o = E[key]
        w(f"| {key} | {o['gm_R']:.3f} | {o['n_inside']} | {', '.join(o['outside'])} | {o['C2a'] and o['C2b']} | {o['verdict']} |")
if "kept fine" in E and "dropped fine" in E:
    Rk, Rd = E["kept fine"]["R"], E["dropped fine"]["R"]
    both = [t for t in Rk if 0.80 <= Rk[t] <= 1.25 and 0.80 <= Rd[t] <= 1.25]
    w(f"\nTests inside the band at both ends of the bracket (fine mesh): {len(both)} of {len(Rk)}.\n")
w("\n### R per test (fine mesh)\n")
w("| Test | stamped | kept | dropped |")
w("|---|---|---|---|")
for t, r in sorted(st["R"].items(), key=lambda x: x[1]):
    k = E.get("kept fine", {}).get("R", {}).get(t); d = E.get("dropped fine", {}).get("R", {}).get(t)
    w(f"| {t} | {r:.3f} | " + (f"{k:.3f}" if k else "n/a") + " | " + (f"{d:.3f}" if d else "n/a") + " |")
(ROOT / "docs" / "G-C1b_addendum_welds_numbers.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
